---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
        name: Terraform FMT
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        name: End of file fixer
      - id: trailing-whitespace
        name: Trailing whitespace fixer
      - id: check-yaml
        name: Check YAML
        args: ['--allow-multiple-documents']
      - id: detect-private-key
        name: Detect Private Key
      - id: mixed-line-ending
        name: Mixed line ending checker
      - id: check-added-large-files
        name: Check for added large files
        args: ['--maxkb=1000']
      - id: pretty-format-json
        name: Pretty Format JSON
        args: ['--autofix']
