---
apiVersion: v1
kind: Namespace
metadata:
  name: backend-app-1
  labels:
    name: backend
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
  namespace: backend-app-1
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    args:
    - sleep
    - "1000000"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-developer-role-binding
  namespace: backend-app-1
subjects:
- kind: User # or Group
  name: # user upn or group object id
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
